apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: hpa-test-llamacpp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-discovery
  namespace: hpa-test-llamacpp
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-discovery
  namespace: hpa-test-llamacpp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-discovery
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: hpa-test-llamacpp
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: hpa-test-llamacpp
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: hpa-test-llamacpp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: hpa-test-llamacpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=7d
        - --storage.tsdb.retention.size=4GB
        image: prom/prometheus:v3.5.0
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config
          readOnly: true
        - mountPath: /prometheus
          name: data
      nodeSelector:
        workload: monitor
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus
      volumes:
      - configMap:
          name: prometheus-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: prometheus-data
