apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: availability-test-transformers
resources:
  - namespace.yaml
  - transformers-base-metric.yaml
  - aiperf.yaml
  - prometheus.yaml
  - kube-state-metrics.yaml
  - grafana.yaml
  - grafana-renderer.yaml
configMapGenerator:
  - name: aiperf-runner
    files:
      - run.sh=aiperf/run.sh
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus/prometheus.yml
      - rules.yml=prometheus/rules.yml
  - name: grafana-datasources
    files:
      - datasources.yaml=grafana/datasources.yaml
  - name: grafana-providers
    files:
      - dashboards.yaml=grafana/dashboards.yaml
  - name: grafana-dashboard
    files:
      - availability.json=grafana/availability.json
