name: aiperf-32-qwen2.5
pod:
  volumes:
  - hostPath:
      path: /models/qwen2.5-0.5b/tokenizer
      type: Directory
    name: tokenizer
  - name: results
    persistentVolumeClaim:
      claimName: aiperf-results-32-qwen2.5
  - emptyDir:
      sizeLimit: 1Gi
    name: tmp
container:
  env:
  - name: DATASET_ENTRIES
    value: '32'
  - name: API_URL
    value: http://base-llamacpp:8000
  - name: MODEL_ID
    value: Qwen/Qwen2.5-0.5B-Instruct
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: CONCURRENCIES
    value: 1,2,4,8
persistence:
  name: aiperf-results-32-qwen2.5
reader:
  volumes:
  - name: results
    persistentVolumeClaim:
      claimName: aiperf-results-32-qwen2.5
