apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec: {{ .Values.persistence.spec | toYaml | nindent 2 }}
