apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.persistence.name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec: {{ .Values.reader | toYaml | nindent 2 }}
