apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pd-comparison-4
resources:
- ../../../gpu-mps/pd/disaggregated
patches:
- target:
    kind: Deployment
    name: pd-decode
  patch: |-
    - op: replace
      path: /kind
      value: StatefulSet
    - op: remove
      path: /spec/strategy
    - op: add
      path: /spec/serviceName
      value: pd-decode
    - op: add
      path: /spec/podManagementPolicy
      value: Parallel
    - op: replace
      path: /spec/replicas
      value: 3
- target:
    kind: Service
    name: pd-decode
  patch: |-
    - op: add
      path: /spec/clusterIP
      value: None
- target:
    kind: Deployment
    name: pd-router
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --decode-urls
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: http://pd-decode-0.pd-decode:8000
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: http://pd-decode-1.pd-decode:8000
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: http://pd-decode-2.pd-decode:8000
